/*
 * This source file was generated by the Gradle 'init' task
 */
package com.cuseto.pong;

import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.Test;

class AppTest {

    @Test       // mock test for repo
    void javaVersionIsAtLeast25() {
        int version = Runtime.version().feature();
        assertTrue(version >= 25, "Expected Java 25+, but got Java " + version);
    }
}
