/*
 * This source file was generated by the Gradle 'init' task
 */
package com.cuseto.pong;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Disabled;

class AppTest {

    @Test       // mock test for repo
    void javaVersionIsAtLeast25() {
        int version = Runtime.version().feature();
        assertTrue(version >= 25, "Expected Java 25+, but got Java " + version);
    }
}
